# 工作流名称
name: "Build and Deploy"

# 启动条件
on:
#   push: # 当有代码推送到仓库时触发
#     branches:
#       - main
#       - master
#     paths-ignore:
#       - .gitignore
#       - README.md
#       - LICENSE
  workflow_dispatch: # 手动触发工作流

# 工作流权限
permissions:
  contents: read
  pages: write
  id-token: write

# 工作流归入pages组，一组工作流只能有一个处于运行状态
concurrency:
  group: "pages"
  cancel-in-progress: true

# 工作流
jobs:
  # 构建
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 拉取所有分支
      
      - name: Test
        run: |
          echo "Hello, Actions!"
          pwd
          ls


  # 部署